# Modules
- color: "fbca04"
  description: "This issue or pull request is related to cloudwatch-log-group module."
  name: ":floppy_disk: cloudwatch-log-group"
- color: "fbca04"
  description: "This issue or pull request is related to cloudwatch-log-policy module."
  name: ":floppy_disk: cloudwatch-log-policy"
- color: "fbca04"
  description: "This issue or pull request is related to cloudwatch-oam-link module."
  name: ":floppy_disk: cloudwatch-oam-link"
- color: "fbca04"
  description: "This issue or pull request is related to cloudwatch-oam-sink module."
  name: ":floppy_disk: cloudwatch-oam-sink"
